nelmio_api_doc:
    areas:
        default:
            path_patterns: [ ^/api ]
    documentation:
        info:
            title: TierList API
            description: API pour la gestion des logos et des tier lists
            version: 1.0.0

